class LargeNumberError(Exception):
    pass

class SubError(Exception):
    pass

class DivError(Exception):
    pass